### ISSUE TITLE
Please add Portuguese (Portugal) support 

### ISSUE THREAD

**Issue by hugok79** [pardus/eta-keyboard#1]
Could they add a Portuguese keyboard?

* QWERTY
* pt-latin1
* https://kbdlayout.info/KBDPO/overview+names

**Comment by mlozturk** [comment]
Thank you for your request.

Unfortunately, since this virtual keyboard is designed for interactive touch screens used in schools, we are unable to add this feature at this time.

However, feel free to fork the project and add the language support yourself.

**Comment by mlozturk** [comment]
Hi @hugok79 ,

I wanted to let you know that Portuguese language support has been added in [v1.0.6](https://github.com/pardus/eta-keyboard/releases/tag/debian%2F1.0.6) version.

Thank you for your suggestion!

**Comment by hugok79** [comment]
@mlozturk Thank you very much!
