### ISSUE TITLE
Misspelled word in Portuguese language

### ISSUE THREAD

**Issue by hugok79** [pardus/eta-keyboard#2]
https://github.com/pardus/eta-keyboard/blob/cce2279311499fc739b5a55bb27e06d9339c35ba/ui/Settings.qml#L54

The word `Brown` in Portuguese is `Castanho`, not `Marrom`.
`Marrom` is used for Brazilian Portuguese(`pt_BR`), not Portuguese(`pt`)

Can this be changed/edited in this file(I can make a PR to change that word) or is this file automatically generated via Qt or a Qt issue( Qt also have `pt_PT` lang code for Portuguese(Portugal)?

**Comment by mlozturk** [comment]
Thank you for the correction! We've updated "Marrom" to "Castanho".

**Comment by hugok79** [comment]
@mlozturk Thank you!
